# Site
title: Demo
# avatar: https://cdn.jsdelivr.net/gh/xaoxuu/assets@master/avatar/avatar.png
logo: https://img.vim-cn.com/d1/4911906ca05da0805cb6dc3e5b44f3d4a4e8a3.png
subtitle:
description:
author: Mr. X
theme: jekyll-theme-slate
